sudo: required
dist: trusty

env: DISPLAY=:99.0

install: true

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
  - metacity --sm-disable --replace &
  - sleep 10 # give metacity some time to start

language: java
jdk:
  - oraclejdk8
python:
  - "3.4"

cache:
  pip: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python-dev
  - sudo apt-get -y install metacity
  - sudo pip3 install -U pip
  - pip3 install --user -r test-requirements.txt coala-bears

script: mvn -X -Dtycho.disableP2Mirrors=true clean verify
