sudo: required
dist: trusty

env: DISPLAY=:99.0

install: true

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
  - metacity --sm-disable --replace &
  - sleep 10 # give metacity some time to start

language: java
jdk:
  - oraclejdk8
python:
  - "3.4"

cache:
  pip: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U pip setuptools virtualenvwrapper
  - sudo pip3 install -U coala-bears
  - sudo apt-get -y install metacity

script: mvn -X clean verify
