sudo: required
dist: trusty

env: DISPLAY=:99.0

install: true

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
  - metacity --sm-disable --replace &
  - sleep 10 # give metacity some time to start

language: java
jdk:
  - oraclejdk8

cache:
  pip: true

before_install:
  - sudo apt-get -y install python3.4-venv
  - python3 -m venv .
  - source ./bin/activate
  - pip3 install -U 'pip<10' 'setuptools<22'
  - pip3 install -r test-requirements.txt coala-bears

script: mvn -X -Dtycho.disableP2Mirrors=true clean verify
